CREATE TABLE IF NOT EXISTS `USER` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ENCRYPTED_ID` varchar(50) NOT NULL,
  `FIRST_NAME` varchar(15) NOT NULL,
  `LAST_NAME` varchar(15) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `PASSWORD` varchar(150) NOT NULL,
  `MOBILE` varchar(10) NOT NULL,
  `GENDER` varchar(6) NOT NULL,
  `ROLES` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`,`EMAIL`,`ENCRYPTED_ID`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`)
) ENGINE=InnoDB;